import numpy

from dlvc import ops
from dlvc.dataset import Dataset, Subset
from dlvc.datasets import pets
import numpy as np

import typing


class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self, data, labels, indices):
        '''
        Ctor.
        '''

        self.data = data
        self.label = labels
        self.idx = indices


class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      label: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: ops.Op = None):
        '''
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is an operation to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        if num > len(dataset) or num <= 0:
            raise ValueError("invalid parameter num")

        if not callable(op) and op is not None:
            raise ValueError("invalid parameter op")

        indices = np.arange(len(dataset))
        if shuffle:
            np.random.shuffle(indices)

        self.batches = [indices[i:i + num] for i in range(0, len(indices), num)]
        self.dataset = dataset

        if (op is None):
            def emptyop(sample: np.ndarray) -> np.ndarray:
                return sample

            op = emptyop

        self.Op = op

    def __len__(self) -> int:
        '''
        Returns the number of batches generated per iteration.
        '''

        return len(self.batches)

    def __iter__(self) -> typing.Iterable[Batch]:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''

        for batch_indices in self.batches:
            yield Batch(
                np.asarray([self.Op(self.dataset[i].data) for i in batch_indices]),
                np.asarray([self.dataset[i].label for i in batch_indices]),
                batch_indices)


##### Validation Checks #####
if True:
    # path = "E:\TU\dlvc\cifar-10-python\cifar-10-batches-py"
    path = "C:\\Users\\tommi\\Desktop\\cifar-10-python\\cifar-10-batches-py"
    ds = pets.PetsDataset(path, Subset.TRAINING)

    op = ops.chain([
        ops.vectorize(),
        ops.type_cast(numpy.float32),
        ops.add(-127.5),
        ops.mul(1 / 127.5),
    ])

    bg = BatchGenerator(ds, num=len(ds), shuffle=True, op=op)
    assert (len(bg) == 1)

    # batch count of batch_size 500 is 16
    batch_size = 500
    bg = BatchGenerator(ds, num=batch_size, shuffle=True, op=op)
    assert (len(bg) == 16)

    last_batch_size = len(ds) - (len(bg) - 1) * batch_size

    # check shapes and data types
    for idx, batch in enumerate(bg):
        expected_batch_size = batch_size if idx < len(bg) - 1 else last_batch_size

        assert batch.data.shape[0] == expected_batch_size
        assert batch.label.shape[0] == expected_batch_size
        assert batch.idx.shape[0] == expected_batch_size
        assert batch.data.shape[1] == 3072

        assert batch.data.dtype == numpy.float32
        assert batch.label.dtype == numpy.int

    # compare values of deterministic batch
    deterministic_batch = [batch for idx, batch in enumerate(BatchGenerator(ds, num=batch_size, shuffle=False, op=op)) if idx < 1][0]
    assert numpy.allclose(deterministic_batch.data[0][0:5], [-0.09019608, -0.01960784, -0.01960784, -0.28627452, -0.20784315])
    assert deterministic_batch.label[0] == 0

    # check whether random batches are indeed random, sample of two sufficient?
    random_batch_1 = [batch for idx, batch in enumerate(BatchGenerator(ds, num=batch_size, shuffle=False, op=op)) if idx < 1][0]
    random_batch_2 = [batch for idx, batch in enumerate(BatchGenerator(ds, num=batch_size, shuffle=False, op=op)) if idx < 1][0]

    assert not numpy.allclose(random_batch_1.data[0], random_batch_2.data[1])

#############################
