from .dataset import Dataset
from .ops import Op
import numpy as np

import typing


class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self, data, labels, indices):
        '''
        Ctor.
        '''

        self.data = data
        self.label = labels
        self.idx = indices


class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      label: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: Op = None):
        '''
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is an operation to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        if num > len(dataset) or num <= 0:
            raise ValueError("invalid parameter num")

        if not callable(Op) and op is not None:
            raise ValueError("invalid parameter op")

        indices = np.arange(len(dataset))
        if shuffle:
            np.random.shuffle(indices)

        self.batches = [indices[i:i + num] for i in range(0, len(indices), num)]
        self.dataset = dataset

        if (op is None):
            def emptyop(sample: np.ndarray) -> np.ndarray:
                return sample

            op = emptyop

        self.Op = op

    def __len__(self) -> int:
        '''
        Returns the number of batches generated per iteration.
        '''

        return len(self.batches)

    def __iter__(self) -> typing.Iterable[Batch]:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''

        for batch_indices in self.batches:
            yield Batch(
                np.asarray([self.Op(self.dataset.data[i][0]) for i in batch_indices]),
                np.asarray([self.dataset.data[i][1] for i in batch_indices]),
                batch_indices)
